# See: https://book.getfoundry.sh/reference/config/overview

[profile.default]
optimizer = true
libs = ["lib"]
src = "source"

[etherscan]
avalanche = { key = "${ETHERSCAN_API_KEY}", url = "https://api.snowscan.xyz/api" }
fuji = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.snowscan.xyz/api" }
